name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # lub "master", jeśli masz inną nazwę głównej gałęzi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Folder, który zawiera zbudowaną stronę
